### ISSUE TITLE
Training phase question ?

### ISSUE THREAD

**Issue by danionescu0** [racai-ai/RobinASR#2]
Will the train phase, use the "deepspeech_final.pth" model or can it be made to enhance this model ? 
I am asking because I just want to improve the model not build one from scratch.

Thanks

**Comment by avramandrei** [comment]
Hi,

Yes, it is possible. Change the `continue_from` parameter in deepspeech_pytorch/configs/train_configs.py with the path to `deepspeech_final.pth`. The model should be initialized with the respective parameters when the training starts.

Let me know if that worked for you.

Bests,
Andrei

**Comment by danionescu0** [comment]
Thanks, i'll give it a try!
