### ISSUE TITLE
model tflite

### ISSUE THREAD

**Issue by nastasev** [racai-ai/RobinASR#3]
Buna ziua,

Ar fi fain si un model pretrained tflite.

Multumesc!

**Comment by avramandrei** [comment]
Buna ziua,

Scuze de raspunsul tarziu.

Da, avem in vedere dezvoltarea unui model tflite. O sa vina intr-o versiune ulterioara.

Cele bune,
Andrei-Marius Avram

**Comment by vinprofessionalapps** [comment]
Buna ziua,

Ati mai apucat ceva cu modelul tflite?

Multumesc!
