### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by pbochan** [racai-ai/RobinASR#4]
Hello Andrei and thanks for sharing the source code and setup instructions for RobinASR. We have successfully setup the environment with the DockerHub and have it up and running. However, we had hard time on accessing the service and using it as we are constantly getting a 404 error. We would appreciate any help regarding this matter.

As a side note, having checked out the demo page - the RobinASR works really good and is an excellent offline solution for Romanian SR. Is there a way we could commercially setup this service on our premises?

Many thanks,
P

**Comment by avramandrei** [comment]
Hello,

Could you tell us at what URL do you try to access the model? As far as I remember, the model is accessed with a POST request at [IP:PORT/transcribe], having attached a wav file sampled at 16k Hz.

Regarding the commercial setup, I am not an expert, but you could theoretically take the docker image and scale it as much as you want using kubernetics. However, you need to pay attention to the inference time (if this is a conern to you), the CPU version is much slower than the GPU version.

Cheers,
Andrei

**Comment by pbochan** [comment]
Hello Andrei and thanks for a reply. We are accessing the service at http://localhost:8080/transcribe using Postman via a POST request and attaching a wav file. We are getting a 404 meaning that we can't access the service altogether.

By commercializing we meant obtaining a working version (either Docker or VMWare or any other image) of the setup and using it on our premises. Is there an option of doing so?

**Comment by pbochan** [comment]
Hello Andrei and thanks for a reply. We are accessing the service at http://localhost:8080/transcribe using Postman via a POST request and attaching a wav file. We are getting a 404 meaning that we can't access the service altogether.

By commercializing we meant obtaining a working version (either Docker or VMWare or any other image) of the setup and using it on our premises. Is there an option of doing so?

**Comment by avramandrei** [comment]
That's a little bit weird. I will pull the docker image later today and I will debug it to see what might be the possible issue.

Also, did you clone the CPU or the GPU version? The GPU version requires an NVIDIA driver.

In addition, the language model of the ASR is quite RAM hungry. The system requires around 16 GB of RAM to run.

The model is distributed under the GNU General Public License v3.0, so you can commercially use this ASR, no issue here. We just need to figure out what is not working for you with this version. Also, we got no other version for ASR except this one. (I hope I got your question right this time)

**Comment by pbochan** [comment]
We are using the CPU version. We have set it up on a mid-low PC with 16GB of RAM and a dual core 3.5GHz - it does require a lot of power but is worth it - no matter we tried using this setup on the demo page - it works like a charm.

Regarding the setup: since we have already spent so much time with this matter and have gotten this far, is there a way you could set it up on our premises so that we get up and running right away? We will negotiate the pricing no problem.

**Comment by pbochan** [comment]
We are using the CPU version. We have set it up on a mid-low PC with 16GB of RAM and a dual core 3.5GHz - it does require a lot of power but is worth it - no matter we tried using this setup on the demo page - it works like a charm.

Regarding the setup: since we have already spent so much time with this matter and have gotten this far, is there a way you could set it up on our premises so that we get up and running right away? We will negotiate the pricing no problem.

**Comment by avramandrei** [comment]
Your hardware setup seems ok. 

Regarding the second issue, let's take this one into a private discussion via email (you have my email on my GitHub profile).
